// <auto-generated />
namespace endep.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migracion1205171939 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migracion1205171939));
        
        string IMigrationMetadata.Id
        {
            get { return "201705130039317_Migracion120517-1939"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
